name: Test module
on: [push]

env:
  SLACK_CHANNEL: wecrm
  SLACK_USERNAME: WeOS CRM
  SLACK_ICON: https://github.com/wepala.png?size=48
  SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
  GOPRIVATE: github.com/wepala/*
  GITHUB_USERNAME: ${{ secrets.GO_MODULES_GITHUB_USERNAME }}
  GITHUB_TOKEN: ${{ secrets.GO_MODULES_TOKEN }}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Configure git for private modules
        run: git config --global url."https://${GITHUB_USERNAME}:${GITHUB_TOKEN}@github.com".insteadOf "https://github.com"
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16.x
      - name: Run Redis tests
        run: go test -v ./... -driver=redis -run TestMain TestEventRepositoryRedis 
      - name: Run unit tests
        run: go test -v ./...
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ env.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}
          role-to-assume: "arn:aws:iam::582726374450:role/Administrator"
          role-duration-seconds: 1200
          role-session-name: sellwithwe${{ github.sha }}
          role-skip-session-tagging: true
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
      - name: Build and tag the image
        run: |
          docker build \
            -t ${AWS_REGISTRY_URL}:${{ github.sha }} \
            -t ${AWS_REGISTRY_URL}:${{ steps.setup.outputs.ticket }} \
            --target app .
      - name: Push to ECR
        run: |
          docker push ${AWS_REGISTRY_URL}:${{ github.sha }}
          docker push ${AWS_REGISTRY_URL}:${{ steps.setup.outputs.ticket }}
      - name: Update ECS service
        run: |
          aws ecs update-service --service sellwithwe${{ steps.setup.outputs.ticket }}-service --cluster ${AWS_CLUSTER_NAME} --force-new-deployment
          dig prod1.weos.sh
      - name: Send success notification
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_COLOR: "#32BD65"
          SLACK_MESSAGE: We were able to test your code without problems, not bad
          SLACK_TITLE: Tests passed
      - name: Send failure notification
        uses: rtCamp/action-slack-notify@v2
        if: failure()
        env:
          SLACK_COLOR: "#FF0000"
          SLACK_MESSAGE: Tests failed. Please review the error in Github Actions
          SLACK_TITLE: Test failed
